# <center>CHOOSING PRIOR 3</center>

---
# Norm $\propto$ norm $\times$ norm (biết variance của  data)

**Công thức:**  
Posterior N<font size="+1">$\left(\frac{n}{n+\frac{\sigma^2_0}{s^2_0}}\overline{X} + \frac{\frac{\sigma^2_0}{s^2_0}}{n+\frac{\sigma^2_0}{s^2_0}}m_0, \frac{\sigma^2_0}{n+\frac{\sigma^2_0}{s^2_0}}  \right) \propto $</font>
Likelihood N$\left( \mu, \sigma^2_0       \right) \times $
Prior N$\left( m_0, s^2_0       \right)  $

Trong đó:
- Các số $\sigma_0, m_0, s_0 $ là biết trước
- $\overline{X}$ là trung bình của data, tức là $\mu$

### Từ posterior mean, ta thấy:
- posterior mean = data *weight* x data mean + sample *weight* x sample mean
- n là data size, $\frac{\sigma^2_0}{s^2_0}$ là effective sample size
- effective sample size là tỉ số giữa variance data và variance prior

### Công thức trên hợp lý, thực vậy:
- Khi $s_0$ lớn, tức prior variance cao, prior không chứa thông tin nhiều
- Sample weight nhỏ so với data weight

### Prior predictive distribution:
- $\int^{\infty}_{-\infty} f(x|\mu)f(\mu)d\mu$
- Có thể nói một data mới $x = \mu + \epsilon, \mu = m_0 +\eta$
- Với $\epsilon \sim N(0, s^2_0), \eta \sim N(0,\sigma^2_0)$
- Vậy:
    - $ x \sim N(m_0, s^2_0 + \sigma^2_0)$
    
### Posterior predictive distribution:  
Tương tự với trên, ta có:  
x $\sim$ N(posterior mean, posterior variance + data variance)


---
# Norm $\propto$ norm $\times$ norm (không biết variance của  data)

Khi ta không biết variance thực sự của data, ta có thể:
1. Chọn một con số thích hợp
2. Tính variance của data rồi áp vào
3. Model variance của data theo phân phối inverse gamma. **bài sẽ nói pp này**

**Công thức:**  
- Giả sử một biến số x:  
$ x \sim N(\mu, \sigma^2) $  
- Prior cho $\mu$:  
$ \mu \sim N(m, \sigma_\mu^2 = \frac{\sigma^2}{w})$ với $ w=\frac{\sigma^2}{\sigma^2_\mu}$  
- Prior cho $\sigma^2$:  
$ \sigma^2 \sim \Gamma^{-1} (\alpha, \beta) $  

Sau khi tính toán, ta có:  
- posterior cho $\sigma^2$:  
$ \sigma^2|X \sim \Gamma^{-1} \left(\alpha +\frac{n}{2}, \beta + \frac{1}{2}\displaystyle\sum_{i=1}^n(X_i -\overline{X})^2 + \frac{nw}{2(n+w)}(\overline{X}-m)^2\right)$   
- posterior cho $\mu$:  
<font size="+1">$ \mu|\sigma^2, X \sim N\left( \frac{n}{n+w}\overline{X} + \frac{w}{n+w}m, \frac{\sigma^2}{n+w}      \right) $</font>  

Để ý mean của posterior $\mu$, ta thấy nó là:  
- data weight x data mean + prior weight x prior mean
- w là effective sample size

Chúng ta có thể tích phân cho $\sigma^2$ để posterior $\mu$ không phụ thuộc nó nữa, khi đó $\mu$ sẽ có phân phối t.  
$\mu|X \sim t$( dof, loc, scale)
- dof = $2\alpha + n$ 
- loc = <font size="+1">$\frac{n\overline{X} + wm}{n+w}$</font>
- scale = <font size="+1">$\sqrt{ \frac{ \beta+ \frac{n-1}{2}s^2 + \frac{nw}{2(n+w)}(\overline{X}-m)^2  }{(n+w)(\alpha + n/2)}  }$</font> với $s^2 = \sum(X_i - \overline{X})^2/(n-1) $ là sample variance.

---

In [ ]:
# Ví dụ về đo nhiệt độ sôi của nước
# Lấy data là nhiệt độ đo được khi nước bắt đầu sôi
# data phân phối theo normal (mean = theta, var = 0.25) (đã biết var)
# Giả sữ prior mean = 100
# Y|theta = N( theta, 0.25); theta = N( 100, s^2)

In [2]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
data = np.array([94.6, 95.4, 96.2, 94.9, 95.9])

In [4]:
# tính var của prior
# giả sử sample effective size = 1
# => s^2 = 0.25

In [5]:
# posterior mean
5/6 * data.mean() + 1/6*100

96.16666666666669

In [6]:
# posterior var
0.25/6

0.041666666666666664

In [7]:
# 95% HPD
st.norm(loc=5/6 * data.mean() + 1/6*100, scale=np.sqrt(0.25/6)).interval(.95)

(95.76659069363707, 96.5667426396963)

In [24]:
# mật độ xác suất theta < 100
st.norm(loc=5/6 * data.mean() + 1/6*100, scale=np.sqrt(0.25/6)).cdf(100)

# cdf =1 nghĩa là 96.16 khác 100 có ý nghĩa thống kê. Tức là thermometer bị sai số xuống giá trị thấp

1.0

In [9]:
# posterior predictive distribution
# N(96.16 , 0.042 + 0.25)
0.042 + 0.25

0.292

---

In [10]:
# Đo trọng lượng bánh của tiệm bánh A
# data phân phối normal không biết mean và variance, n = 27
# trong luong ~ N( mean, sigma^2)
# mean ~ N(m , sigma^2/w), effective sample size w=0.1 do không chắc lắm
# mình dự đoán m = 500
# sigma^2 ~ Inverse Gamma (a=3, b=200); trung bình là 100

# prior mean
m = 500
w = 0.1

# prior sigma^2
a = 3
b = 200

# data
n = 27
x = 609.7
s2 = 401.8

In [11]:
# rvs(n) là sampling n mẫu
prior_sigma_rvs = st.invgamma(a=a, scale=b).rvs(300)
prior_sigma_rvs.mean()

101.0469403289876

In [12]:
# posterior sigma^2
alpha = a + n/2
beta = b + (n-1)/2*s2 + w*n/ ( 2*(w+n)) * (x-m)**2
alpha, beta

(16.5, 6022.884188191883)

In [21]:
# posterior mu 
mu_mean = (n*x + w*m)/(n+w)
mu_mean

622.3920265780731

In [25]:
# sampling posterior mu mean
posterior_sigma_rvs = st.invgamma(a=alpha, scale=beta).rvs(1000)

posterior_mu_rvs = st.norm(loc=mu_mean, scale = np.sqrt(posterior_sigma_rvs)).rvs(1000)

# sampling 20 times for mu mean
posterior_mu_rvs[:20]

array([580.20626547, 622.97471542, 645.71078519, 607.97156194,
       611.60016382, 598.9312222 , 622.54240042, 627.13735753,
       646.93210967, 599.29825861, 616.30839812, 616.04647995,
       625.95658522, 585.84716002, 626.24947281, 589.01221409,
       604.2830409 , 625.48290231, 626.85108175, 617.35856515])

In [27]:
posterior_sigma_rvs

array([ 901.61477886,  674.99949499,  281.79786583,  362.65176087,
        412.06942598,  370.94512881,  355.79979443,  333.30277171,
        460.43941613,  410.88838886,  311.94503727,  418.4634486 ,
        427.58462818,  339.92924335,  490.91589411,  318.27438414,
        405.82586263,  345.52573657,  443.70492754,  439.32424041,
        566.23243454,  386.69844593,  405.62542492,  372.56773709,
        345.69808852,  469.6229176 ,  371.00849884,  640.25594765,
        441.23048784,  404.09187936,  270.71460541,  350.63787593,
        399.10483074,  349.78087839,  322.84678135,  427.66688122,
        325.13381876,  616.80152133,  366.05176028,  398.09658089,
        354.95716041,  364.72677158,  527.14863342,  554.00859103,
        357.57678542,  524.89181926,  382.29025004,  336.22597309,
        403.87021487,  217.01512688,  426.37617209,  580.73322281,
        269.37931207,  296.86719806,  421.15626601,  458.78602289,
        300.73998711,  535.62657671,  416.88302497,  318.69190

In [26]:
# 95% CI for posterior mu
np.quantile(posterior_mu_rvs, [0.025, 0.975])

array([583.79843626, 663.94979443])

In [16]:
# data ở một tiệm bánh B
# prior mean
m = 500
w = 0.1

# prior sigma^2
a = 3
b = 200

# data
n = 30
x = 622.8
s2 = 403.1

In [17]:
alpha = a + n/2
beta = b + (n-1)/2*s2 + w*n/ ( 2*(w+n)) * (x-m)**2
mu_mean = (n*x + w*m)/(n+w)
posterior_sigma_rvs = st.invgamma(a=alpha, scale=beta).rvs(1000)
posterior_mu_rvs_B = st.norm(loc=mu_mean, scale = np.sqrt(posterior_sigma_rvs)).rvs(1000) # B là tiệm bánh B
np.quantile(posterior_mu_rvs_B, [0.025, 0.975])

array([583.18218392, 661.71146829])

In [18]:
# Null hypothesis: tiệm bánh B tốt hơn tiệm bánh A
# tức là bánh ở tiệm B nhiều hơn bánh ở tiệm A
# lấy n mẫu từ posterior mu ở B so sánh với n mẫu từ posterior mu A. Sau đó cộng lại chia n
np.sum(posterior_mu_rvs_B > posterior_mu_rvs)/1000

0.66